Harmonise abnormal morphology labels
obophenotype/human-phenotype-ontology pull request #10029
Opened 2023-08-31 17:01 UTC by matentzn

fixes #10027 

@pnrobinson please review the [diff](https://github.com/obophenotype/human-phenotype-ontology/pull/10029/files) bit carefully, because some renamings do not sound particularly beautiful:

<img width="1371" alt="image" src="https://github.com/obophenotype/human-phenotype-ontology/assets/7070631/2aff4971-0540-452d-8efb-5dc15dd751ba">

2023-08-31 17:09 UTC, pnrobinson commented
I will check but prob in Sept. It would also be good to add the label being replaced as an exact synonym in case anybody has gotten used to it

2023-08-31 17:19 UTC, matentzn commented
I added the synonyms!

2023-10-04 10:20 UTC, pnrobinson requested changes
Thanks! All is great but could we change the following three labels
1. Abnormal vestibule of the inner ear morphology
->Abnormal morphology of the vestibule of the inner ear

2. Abnormal nerves of the inner ear morphology
-> Abnormal inner ear nerve morphology

3. Abnormal papillary muscles morphology
->Abnormal papillary muscle morphology

2023-10-04 10:27 UTC, pnrobinson approved these changes

2023-10-04 10:42 UTC, merged